main: io.github.aluria.region.RegionGuardPlugin
author: zkingboos_
version: 1.0.0-SNAPSHOT
name: AluriaRegionGuard
softdepend:
  - Common-Bukkit
#commands:
#  region:
#    description: "Command to create defined regions"